name: Update container image lambda DEV

on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  update:
    uses: ./.github/workflows/my_workflow.yml
    with:
      aws_account_id: 634847813792
      aws_region: us-east-1
      ecr_repository_name: serverless-clambda-av-dev
      function_name: clambda-av-dev-virusScan
      image_tag: clambdaAv
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
